name: Publish
on:
  push:
    tags:
      - '*.*.*.*'
jobs:
  Plugin:
    permissions:
      contents: write
    runs-on: windows-latest
    env:
      REPO_NAME: ${{ github.repository }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Environment Variables
        run: |
          $tag = "${{ github.ref }}" -replace 'refs/tags/', ''

          "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Restore Nuget Packages
        run: dotnet restore Gatherbuddy/Gatherbuddy.csproj

      - name: Build Plugin
        run: dotnet build --no-restore -c Release Gatherbuddy/Gatherbuddy.csproj -p:SecretKey=${{ secrets.GITHUB_TOKEN }} -p:AssemblyVersion=${{ env.tag }} -p:FileVersion=${{ env.tag }} -p:PackageVersion=${{ env.tag }} -p:InformationalVersion=${{ env.tag }} --output .\build

      - name: Zip Plugin
        run: Compress-Archive -Path .\build\* -DestinationPath .\build\GatherbuddyReborn.zip

      - name: Publish Plugin
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/GatherbuddyReborn.zip
          token: ${{ secrets.GITHUB_TOKEN }}

  Web:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Environment Variables
        shell: pwsh
        run: |
          $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
          
          "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV

      - name: Set Lowercase Repo Name
        run: echo "REPO_NAME_LOWER=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          install: 'true'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Web Service
        run: docker build . -f ./GatherBuddy.Web/Dockerfile --build-arg SECRET_KEY=${{ secrets.GITHUB_TOKEN }} -t ghcr.io/${{ env.REPO_NAME_LOWER }}:${{ env.tag }} --quiet --load

      - name: Tag Docker Image
        run: docker tag ghcr.io/${{ env.REPO_NAME_LOWER }}:${{ env.tag }} ghcr.io/${{ env.REPO_NAME_LOWER }}:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME_LOWER }}:${{ env.tag }}
          docker push ghcr.io/${{ env.REPO_NAME_LOWER }}:latest
